title: 'Adept Camp'
default_lang: en
author:
  name: AC
  email: duncan@egroup.com.au
taxonomies:
  - category
  - tag
metadata:
  description: ''
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
